### ISSUE TITLE
Page scrolling impossible on iOS if this plugin is installed

### ISSUE THREAD

**Issue by derwaldgeist** [cjpearson/cordova-plugin-keyboard#14]
In principle, the plugin is working in my app. But I noticed a strange phenomenon on iOS: If I add this package, no page scrolling is possible anymore on iOS (which in fact breaks my app). As soon as I remove the plugin, everything is back to normal.

This only happens on the main body. If I include a div with an autoscroll behaviour, I am able to scroll this div. But the main page itself is unscrollable.

Any idea what might be causing this?

**Comment by mbackschat** [comment]
Hello, I also had this problem. I created a fork with a simple fix you might try: https://github.com/mbackschat/cordova-plugin-keyboard
I this work for you too, I will create a pull request.

**Comment by cjpearson** [comment]
@mbackschat, thanks for looking into this. I completely missed this issue. Feel free to create a PR.
