### ISSUE TITLE
Cannot build project after download

### ISSUE THREAD

**Issue by huxdr** [cjpearson/cordova-plugin-keyboard#2]
After I download this plugin into my Apache Cordova app for Visual Studio my project will no longer build.  I get this error when i try to debug in Android:

![image](https://cloud.githubusercontent.com/assets/13219580/8723252/406a8794-2b9a-11e5-9362-53e7f1fb0db9.png)

I haven't used any methods or calls to this plugin in my code yet and the only call to this plugin i have in my project is this in my config.xml:

![image](https://cloud.githubusercontent.com/assets/13219580/8723295/97ba9d68-2b9a-11e5-97ad-49353569be0a.png)

I have the contacts, cordova call number, cordova sms, geolocation, launch navigator, and splashscreen plugins installed as well if it helps at all.

thanks

**Comment by cjpearson** [comment]
I've updated the plugin to support cordova android 3.x as well. If you upgrade the plugin version to 1.1.1, it should work.
