### ISSUE TITLE
Will this cause App Rejections when using WKWebView?

### ISSUE THREAD

**Issue by rect1fy** [cjpearson/cordova-plugin-keyboard#21]
Similar plug-in is causing app rejections due to hide the accessory bar implementation... 
https://github.com/driftyco/ionic-plugin-keyboard/issues/179

Is this a problem with this plug-in as well?

**Comment by cjpearson** [comment]
I haven't heard of any app rejections, but we do use the same `@"UIWebBrowserView"` string that is causing those ionic rejections, so it is possible. I'll look into obfuscating this or removing it completely. Unfortunately, there is no public API for hiding the accessory bar so we have to use some less than ideal solutions.

**Comment by cjpearson** [comment]
If you want to be safe, comment out these lines before compiling your app store build. https://github.com/cjpearson/cordova-plugin-keyboard/blob/master/src/ios/CDVKeyboard.m#L124-L140

**Comment by cjpearson** [comment]
I made a change so UIWebBrowserView no longer shows up when using the strings tool. That appears to have been what caused the rejections for Ionic users. Upgrade to 1.1.4 for this fix. If anyone reports an app store rejection, I'll reopen this issue.
