### ISSUE TITLE
[WKWebView] Keyboard.onshowing always undefined so keyboard is not appearing

### ISSUE THREAD

**Issue by danlg** [cjpearson/cordova-plugin-keyboard#23]
I have a Meteor 1.3 app with WKWebView (iOS) and the keyboard is not appearing (when plugging cordova-plugin-keyboard). I found out that Keyboard.onshowing always undefined so keyboard is not appearing.

I have tried to remove completely the cordova plugin (as actually I don't need to customize anything but need the bloody keyboard to appear, which make me wonder whether an actual cordova keyboard plugin is required at all).  And no luck either so I came across this bug nasty bug:

> calling element.focus() from -[WKWebView evaluateJavaScript
> https://bugs.webkit.org/show_bug.cgi?id=142757 

which I wonder is not the root cause of my issue and is a native webkit bug. If this is the case, I wonder just how people could get around it ? 

I'm knocking my head on the wall to fix this issue (just need a keyboard to type in an input field which is not really cutting-edge)

**Comment by cjpearson** [comment]
Keyboard.onshowing is undefined by default. You can set it to a function to be called when the keyboard shows.

Are you running the app in the simulator or do you have an external keyboard attached? The on screen keyboard will not show if there is an external keyboard.
