### ISSUE TITLE
Keyboard.hide() not working 

### ISSUE THREAD

**Issue by shivam5x** [cjpearson/cordova-plugin-keyboard#24]
Hi,
  I am using Keyboard.hide(); method to hide keyboard and the scenario is when i click over text (input)(Specific one where i am performing datepicker ) so it is show both datapicker and keyboard.

So i just followed your instruction to hide like -
$('#reg_form_date').click(function(){
                console.log("Keyboard hide")
                Keyboard.hide();
            })
but it is not working in both android and ios.

Please let me know the solution.

Thanks
Shivam

**Comment by TawabG** [comment]
Do you get any sort of error message?

Also, in iOS you've got to actually BUILD the app(with a p12 file and provisioning file) for a 3rd party plugin to work.

**Comment by mavillar** [comment]
I have the same problem.

I have a search input and when clicked on done, the keyboard should close.

What's the p12 file and provisioning file? could you post a link?

**Comment by cjpearson** [comment]
@shivam5x Is it possible the click is immediately reopening the keyboard? What if you put `Keyboard.hide()` inside a timeout?

@mavillar Have you tried calling `Keyboard.hide()` from the JS console? If it works there, then it may be an issue with your done click handler.

Apple has [some information](https://developer.apple.com/support/code-signing/) on code signing. The plugin should work in the simulator and on a device though.
