### ISSUE TITLE
status bar height disappearing

### ISSUE THREAD

**Issue by pwbs** [cjpearson/cordova-plugin-keyboard#27]
Hi,

I'm using something like

``` Objective-C
- (void)viewWillAppear:(BOOL)animated {
    if ([[[UIDevice currentDevice] systemVersion] floatValue] >= 7) {
        CGRect viewBounds = [self.webView bounds];
        viewBounds.origin.y = 20;
        viewBounds.size.height = viewBounds.size.height - 20;
        self.webView.frame = viewBounds;
    }
    [super viewWillAppear:animated];
}
```

from http://stackoverflow.com/questions/19209781/ios-7-status-bar-with-phonegap
which give 20px to the top status bar.

When I activate the shrink (via `Keyboard.shrinkView(true)`), the top bar space becomes 0 (and it doesn't go back to 20px when `Keyboard.shrinkView(false)` is executed.

**Comment by cjpearson** [comment]
There is logic for this in the plugin itself. Try adding this preference to your config.xml
`<preference name="StatusBarOverlaysWebView" value="false" />`

You may also want to add the status bar plugin.

**Comment by pwbs** [comment]
Thanks for your help!
