### ISSUE TITLE
Can shrinkView solve the iOS keyboard going on top of focused inputs?

### ISSUE THREAD

**Issue by slorber** [cjpearson/cordova-plugin-keyboard#29]
Hi,

I have a problem where in some cases the iOS keyboard opens on top of a text input that just get focused. Does anyone have any advice on how this plugin could (or not) solve this problem?

I've explained that problem better here:
http://stackoverflow.com/questions/38077603/avoid-hiddin-input-behind-ios-keyboard-for-for-browser-cordova-similar-to-iqke

For me it seems shrinking the viewport might be a solution to this problem, but I'd appreciate any feedback because I'm certainly not alone having had this problem and it's touchy so I might break something on an iOS version without noticing :(

Also If you succeed to solve this problem, which viewport meta tag did you use in the html file? Someone reported that he had to use 2 different metatag for android / iOS:

```
<!-- IOS -->
<meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0, target-densityDpi=device-dpi" />`
<!-- ANDROID -->
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=1" />
```

**Comment by cjpearson** [comment]
I think it should work. There may be some combinations of absolute/fixed position that don't work properly though. A few people have reported issues that I'm unable to reproduce.

For reference I have this viewport tag. `<meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />`

**Comment by slorber** [comment]
Thanks.
Are you using this for both android/ios?

Isn't iOS supposed to use width=980px if you don't set `width=device-width` ? I've read that somewhere

**Comment by cjpearson** [comment]
Android is the same, but that shouldn't affect this plugin since it doesn't do any resizing for android. I'm not too familiar with the viewport tag. The app I'm working on now uses kendo which handles setting the tag.

**Comment by troggy** [comment]
> Does anyone have any advice on how this plugin could (or not) solve this problem?

In my app I have a textarea with `position: fixed` and `bottom: 0`. It was covered by keyboard on iOs. Using this plugin and `shrinkView` solved the problem.
