### ISSUE TITLE
Chinese & Japanese Keyboards will damage shrinkView

### ISSUE THREAD

**Issue by puny-d** [cjpearson/cordova-plugin-keyboard#3]
But it will damaged WebView when I tapped any words with Chinese or Japanese Keyboard, because these keyboards have a dynamic additional bar for select these input method words

**Comment by cjpearson** [comment]
Could you share a screenshot of what it looks like? Are you hiding the accessory bar? What version of iOS are you using?

**Comment by puny-d** [comment]
Yes, when I set hideFormAccessoryBar to true, the Chinese keyboard works well on the first init in app, but when the keyboard open again, it will damaged WebView when I tapped any words, it will cause the status bar to black in iOS, and push the WebView down.

The iOS version is 8.3,  But when I set hideFormAccessoryBar to false in Chinese keyboard, it works well.

![img_3822](https://cloud.githubusercontent.com/assets/3891276/8866367/2b47edf2-31ee-11e5-8623-fec23ab506eb.PNG)

**Comment by cjpearson** [comment]
Thanks for the details. I've pushed a change to how hideFormAccessoryBar and the status bar works. Try installing the plugin using the github URL and see if it fixes the problem.

**Comment by puny-d** [comment]
Thank very much !!   The problem has solved.
But there is a small problem，there will be a black line beyond the Chinese keyboard.
![img_3854](https://cloud.githubusercontent.com/assets/3891276/8881191/93cb03fa-3270-11e5-9f79-42cfbb4957ca.PNG)

**Comment by cjpearson** [comment]
I'm having trouble reproducing this situation. How do you get that specific chinese keyboard?

**Comment by puny-d** [comment]
Just add new keyboard, choose Chines(Simplified)-> Pinyin-10 key, Thank you!

![img_3979](https://cloud.githubusercontent.com/assets/3891276/8978987/5f5bb2dc-36d9-11e5-879c-369397fcf197.PNG)
![img_3980](https://cloud.githubusercontent.com/assets/3891276/8978988/5f5ec512-36d9-11e5-8724-54f510a69d98.PNG)

**Comment by cjpearson** [comment]
I'm sorry I'm having trouble reproducing this last issue. Also, apparently the 10 Key keyboard is only available on phones from China. If you can reproduce the issue in a small sample project, I can take another look.

**Comment by puny-d** [comment]
OK，and thank you very much, you did good job!
