### ISSUE TITLE
Error: events.forwardEventsTo is not a function

### ISSUE THREAD

**Issue by mavillar** [cjpearson/cordova-plugin-keyboard#30]
When installing the plugin, the following error arises:

![captura de pantalla 2016-07-10 a las 12 52 30](https://cloud.githubusercontent.com/assets/3111892/16713109/3bdf217a-469d-11e6-8202-ce94f3351360.png)

**Comment by cjpearson** [comment]
I haven't seen anything like that before. What cordova/node versions are you using? Do other plugin installs work correctly?

**Comment by mavillar** [comment]
I solved it just reinstalling all again.
