### ISSUE TITLE
iOS10 webview resize bugs

### ISSUE THREAD

**Issue by kristfal** [cjpearson/cordova-plugin-keyboard#34]
iOS10 introduces a bug that is exposed when calling `window.Keyboard.shrinkView();`:

When opening the keyboard with and `window.Keyboard.shrinkView(true);` iOS9 would resize the GUI and a `window.onresize` event would fire. In iOS10, the GUI is not resized (elements that would overflow and create a scrolling context does not scroll).

In order for the overflowing elements to be scrollable, one has to manually update (remove and reset) the `overflow` CSS propery on the overflowing DIV after the keyboard has entered the view.

**Comment by cjpearson** [comment]
Are you using UIWebView or WKWebView?

**Comment by kristfal** [comment]
@cjpearson Only tested in WKWebView.

**Comment by cjpearson** [comment]
It may be related to #32. The changelog for the WebKit bug mentions that it no longer fires resize events.

**Comment by beijiyibei** [comment]
The same problem, do not know how to solve

**Comment by cjpearson** [comment]
Closing this as I think #32 fixed it. It should work in 1.1.5. Let me know if you still see this issue.
