### ISSUE TITLE
MeteorJS Integration

### ISSUE THREAD

**Issue by garyfoo** [cjpearson/cordova-plugin-keyboard#4]
Hello! I have tried using your plugin with MeteorJS Cordova but the Keyboard functions doesn't seem to be working. Could this be a MeteorJS compatibility issue with this package?

**Comment by jfrux** [comment]
Seems unlikely that it's incompatible.

Are you certain youre running it within on("deviceready")?

**Comment by garyfoo** [comment]
I am running it on `document.addEventListener("deviceready", function() {}, false);`

Should I use `document.on();` instead?

**Comment by jfrux** [comment]
Nono, sorry. That's fine.

Was honestly just pseudo codin' hah

Umm... I'm not very familiar with meteor sadly.

Could you share your code inside device ready?

**Comment by garyfoo** [comment]
<img width="398" alt="screen shot 2015-09-09 at 10 18 45 pm" src="https://cloud.githubusercontent.com/assets/5109700/9761610/2fcb8302-5741-11e5-84cc-be8f81d2198d.png">

Currently I'm coding it like this.. not sure if I'm getting the syntax wrong but the KeyBoard object is definitely not working in this code

**Comment by cjpearson** [comment]
Is the keyboard object not defined or is it doing nothing? What device are you using? I'm not sure if this is an issue with meteor, but I've never used it.

**Comment by chriswessels** [comment]
@gfmr90 Instead of the `deviceready` event, try using `Meteor.startup`. This should only run after `deviceready` has fired on Cordova devices.

``` javascript
Meteor.startup(function () {
  /* Calls to `Keyboard` object here */
});
```

**Comment by aesmon** [comment]
`Meteor.startup(function () {
  if (Meteor.isCordova) {
    Keyboard.hideFormAccessoryBar(true);
    Keyboard.shrinkView(false);
    StatusBar.hide();
  }
});`

This works fine for me.
