### ISSUE TITLE
Auto suggestion text not working on SVG iOS Cordova ionic

### ISSUE THREAD

**Issue by AgNm** [cjpearson/cordova-plugin-keyboard#43]
I have created a cordova ionic app. I have an Editor page, which I'm opening using window.open('editor.html');

I have an SVG Canvas in it, When my keyboard is opening, I'm tapping on auto suggestion text. The auto suggestions are working for input type but not with SVG text.

But it is not displaying until I tap on space bar. How can I make it working. I have added cordova-plugin-keyboard as well.

**Comment by cjpearson** [comment]
@AgNm, I'm not sure I follow. Do you have a simple demo app that shows this issue?

**Comment by AgNm** [comment]
@cjpearson please check this link:
https://www.dropbox.com/s/eaodpmttefrck93/Autosuggestion.mov?dl=0

The auto suggestion text is not getting typed on clicking the text. Its only getting typed when I clicked on space bar. This is an SVG. Auto suggestion is working fine with input type.

**Comment by AgNm** [comment]
@cjpearson have you got time to check it?
