### ISSUE TITLE
Is Possible

### ISSUE THREAD

**Issue by edvenkat** [cjpearson/cordova-plugin-keyboard#44]
How i can add "KeyboardType" and "ReturnType".Please advice

**Comment by cjpearson** [comment]
This plugin does not support changing those right now. You can look at the dark branch for an example of changing `keyboardAppearance` which like `returnKeyType` and `keyboardType` is a property of `UITextInputTraits`. That solution involves swizzling private APIs though, so it may not work in future updates to iOS.

**Comment by edvenkat** [comment]
Thanks it is working... how to dynamically handle ? I can't get pass value from js in plugin iniitaize method please advice

**Comment by upworkvenkat** [comment]
I have created the function for change return type but i don't know how to change based upon pass value from js....please advice @cjpearson
