### ISSUE TITLE
KeyboardShrinksView in iOS InAppBrowser

### ISSUE THREAD

**Issue by danielflippance** [cjpearson/cordova-plugin-keyboard#49]
Thanks for your comments on https://stackoverflow.com/a/33590427/2325676 regarding shrinking the InAppBrowser view on iOS when the keyboard is shown.

Do you have any advice on extending this plugin to support KeyboardShrinksView on the iOS InAppBrowser? Could the work be achieved solely in this plugin or do you think it would require a change to the InAppBrowser as well?

I may have some time to make the change.

**Comment by cjpearson** [comment]
I think it would have to be implemented in the InAppBrowser plugin, but you could probably reuse some of the code. All plugins are given a reference to the main Cordova webview, but I don't know of any clean way to control the views created by another plugin.
