### ISSUE TITLE
What platforms does this work on?

### ISSUE THREAD

**Issue by SamMakesCode** [cjpearson/cordova-plugin-keyboard#69]
Just curious what platforms this works on because I've tried in Phonegap Developer on iOS and in the browser and neither have shrunk the webview when the keyboard comes up.

With that said, the body is absolutely positioned to the top left and is 100% wide and high. Am mis-using this plugin?

**Comment by Aarbel** [comment]
Works here for pure Cordova and iOS

**Comment by SamMakesCode** [comment]
@Aarbel Do you have to deploy to iOS to test it?

**Comment by Aarbel** [comment]
I test it with Iphone simulator with XCode, or directly on my Iphone with Xcode

**Comment by cjpearson** [comment]
This plugin only supports iOS and Android. It won't work in the Phonegap Developer App, because the Phonegap Developer App does not install this plugin. http://docs.phonegap.com/references/developer-app/troubleshoot-faq/
