### ISSUE TITLE
Installation Fails

### ISSUE THREAD

**Issue by superjoefly** [cjpearson/cordova-plugin-keyboard#73]
I'm using Cordova v7.0.1

The following command: `cordova plugin add cordova-plugin-keyboard`
returns the following errors:

Error: Failed to fetch plugin cordova-plugin-keyboard via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 216 Error output:
npm ERR! path /home/joey/webdev/PROJECTS/quasar-todo/cordova/node_modules/cordova-plugin-device/npm-shrinkwrap.json
npm ERR! code ELOOP
npm ERR! errno -40
npm ERR! syscall open
npm ERR! ELOOP: too many symbolic links encountered, open '/home/joey/webdev/PROJECTS/quasar-todo/cordova/node_modules/cordova-plugin-device/npm-shrinkwrap.json'

My connection is fine, so I'm not really sure what this means or what to do with it.

Any assistance is greatly appreciated.

Thanks :-)

**Comment by Aarbel** [comment]
did you solved the issue ?

**Comment by superjoefly** [comment]
No, I haven't.

**Comment by Aarbel** [comment]
could you give more infos about the environment ? OS etc... do you run a vpn ?

**Comment by superjoefly** [comment]
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

No VPN

HP Elitebook 840 G1

This is a Quasar Framework project wrapped with Cordova.

I believe it may have something to do with this path:
`cordova/node_modules/cordova-plugin-device/npm-shrinkwrap.json`

`cordova-plugin-device`  is a file, not a folder, on my system.

Any other info that could be helpful, please let me know.

**UPDATE | FIXED: That was the problem...removed the file `cordova-plugin-device` and it installed.**

Thanks for your help :-)

**Comment by Aarbel** [comment]
@superjoefly close your issue ;)
