### ISSUE TITLE
Webview is distorted when I call shinkView(true)

### ISSUE THREAD

**Issue by laychar** [cjpearson/cordova-plugin-keyboard#78]
Following is my code.
$function({
   window.addEventListener('keyboardDidSho 
  w', function () {
     Keyboard.shrinkView(true);
  });
});

Would you give me adivce for me to solve this problem?

**Comment by zspencer** [comment]
I think you may want to look into #77.

**Comment by cjpearson** [comment]
Closing in favor of #77. If it's not a dupe, please re-open.
